import json
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI(
    title="ISRO PS14 Space Weather API",
    description="Real-time Geostationary Electron Flux Prediction API",
    version="1.0.0"
)

# Allow CORS for your frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

PROJECT_ROOT = Path(__file__).parent
LIVE_STATE_FILE = PROJECT_ROOT / "outputs" / "live" / "live_state.json"

class ForecastData(BaseModel):
    timestamp: str
    current_flux_gt2MeV: float
    status: str
    horizons: List[str]
    predictions_pfu: List[float]
    p5_pfu: List[float]
    p95_pfu: List[float]
    uncertainty: List[float]

@app.get("/api/status")
async def get_system_status():
    """Check if the backend is running."""
    return {"status": "operational", "service": "ISRO PS14 Backend API"}

@app.get("/api/live", response_model=ForecastData)
async def get_live_forecast():
    """
    Get the latest real-time predictions generated by the background daemon.
    """
    if not LIVE_STATE_FILE.exists():
        raise HTTPException(status_code=503, detail="Live state not available. Ensure the daemon is running.")
        
    try:
        with open(LIVE_STATE_FILE, "r") as f:
            data = json.load(f)
        return data
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error reading live state: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    # Run the server on port 8000
    uvicorn.run(app, host="0.0.0.0", port=8000)
